apiVersion: v1
kind: Service
metadata:
  name: insurance-policy-service
spec:
  selector:
    app: insurance-policy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer